import "./globals.css";
import MobileNav from "./components/MobileNav/MobileNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/rgm1dlw.css" />
      </head>
      <body className="bg-slate-900 font-[sofia-pro,_sans-serif] font-medium not-italic text-slate-100/70 antialiased">
        <MobileNav />
        {children}
      </body>
    </html>
  );
}
